### ISSUE TITLE
Doesn't work on Cygwin: RTLD_NEXT undeclared

### ISSUE THREAD

**Issue by unnikrishnanta** [bingmann/malloc_count#7]
Although the documentation is hopeful about the code working as expected on Cygwin and MingW, the code fails to compile on Cygwin. This is because `RTLD_NEXT` is a glibc extension that is not supported by Cygwin (as far as I know). I get the following compilation error on Cygwin running on a Windows machine. 

```
malloc_count.c:341:38: error: ‘RTLD_NEXT’ undeclared (first use in this function); did you mean ‘RTLD_NOW’?
  341 |     real_malloc = (malloc_type)dlsym(RTLD_NEXT, "malloc");
      |                                      ^~~~~
      |                                      RTLD_NOW
```
It will be great if there are alternatives to make this work on Cygwin.

**Comment by bingmann** [comment]
Sorry, `RTLD_NEXT` is a dynamic linker (dl) extension not available in Windows, because `.dll`s work differently.
